version: '3'

services:
  app:
    image: node:18
    container_name: stock_json_backend
    ports:
      - 8000:8000
    tty: true
    volumes:
      - ./src:/src
    working_dir: "/src"
    command: node index.cjs
  db:
    image: postgres
    container_name: postgres
    volumes:
      - db-store:/var/lib/postgresql/data
      - ./script:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=passw0rd # change me!
      - POSTGRES_HOST=localhost
volumes:
  db-store:

